### ISSUE TITLE
about "/traintestlist/xxxxxx.txt"

### ISSUE THREAD

**Issue by shiwen1997** [ShihaoZhaoZSH/Video-Backdoor-Attack#1]
hi! thank you for your open source code.
Could you please provide the code to generate  "/traintestlist/xxxxxx.txt" base on my own dataset-path?
P.S.
enhance_trigger.txt
generate_trigger.txt
test_bad_model.txt
test_clean_model.txt
train_bad_model_eps8_port30_ts24.txt
train_clean_model.txt

**Comment by shiwen1997** [comment]
看到作者是复旦的大佬，原谅我直接用中文......
第2个问题就是 您能提供一下 把UCF101数据集处理成frame的代码 吗？因为LossNAN/I3D-Tensorflow里面提供的数据预处理的代码好像只能对单个avi预处理

**Comment by ShihaoZhaoZSH** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    同学，你好：对于你的两个问题，我在这里做一下解答。1. 附件1为数据集生成frame的代码。2. 对于github repo里traintestlist中的文件生成：附件2是ucf101提供的原始训练测试集的划分文件。github repo里traintestlist中的各个文件是根据这些原始划分文件生成的，文件中每行里第一个为样本路径，第二个为视频所包含的帧数，第三个为数据的标注类别。对于生成github repo里这些文件的方法，首先需要利用原始划分文件以及视频提帧的frame数量，生成包含frame数的训练测试文件；然后，在根据不同的模块（如train/test，enhance/generate trigger等）的需求（如target class，污染数据的比例等），对所需样本、标注类别等进行采样、改变。这些都是简单的操作，比如python中的文件操作、os、random模块等；如果不清楚采用何种策略来采样和改变标注，可以详细的阅读论文中的对应板块，并参照github repo里的实现来更好的理解。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1834785143
                            
                    
                        
                            
                                    1834785143@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 12/23/2020 09:01，shiwen1997<notifications@github.com> wrote： 




看到作者是复旦的大佬，原谅我直接用中文......

第2个问题就是 您能提供一下 把UCF101数据集处理成frame的代码 吗？因为LossNAN/I3D-Tensorflow里面提供的数据预处理的代码好像只能对单个avi预处理



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ShihaoZhaoZSH** [comment]
同学，你好：对于你的两个问题，我在这里做一下解答。1. 附件1为数据集生成frame的代码。2. 对于github repo里traintestlist中的文件生成：附件2是ucf101提供的原始训练测试集的划分文件。github repo里traintestlist中的各个文件是根据这些原始划分文件生成的，文件中每行里第一个为样本路径，第二个为视频所包含的帧数，第三个为数据的标注类别。对于生成github repo里这些文件的方法，首先需要利用原始划分文件以及视频提帧的frame数量，生成包含frame数的训练测试文件；然后，在根据不同的模块（如train/test，enhance/generate trigger等）的需求（如target class，污染数据的比例等），对所需样本、标注类别等进行采样、改变。这些都是简单的操作，比如python中的文件操作、os、random模块等；如果不清楚采用何种策略来采样和改变标注，可以详细的阅读论文中的对应板块，并参照github repo里的实现来更好的理解。

**Comment by shiwen1997** [comment]
> 同学，你好：对于你的两个问题，我在这里做一下解答。1. 附件1为数据集生成frame的代码。2. 对于github repo里traintestlist中的文件生成：附件2是ucf101提供的原始训练测试集的划分文件。github repo里traintestlist中的各个文件是根据这些原始划分文件生成的，文件中每行里第一个为样本路径，第二个为视频所包含的帧数，第三个为数据的标注类别。对于生成github repo里这些文件的方法，首先需要利用原始划分文件以及视频提帧的frame数量，生成包含frame数的训练测试文件；然后，在根据不同的模块（如train/test，enhance/generate trigger等）的需求（如target class，污染数据的比例等），对所需样本、标注类别等进行采样、改变。这些都是简单的操作，比如python中的文件操作、os、random模块等；如果不清楚采用何种策略来采样和改变标注，可以详细的阅读论文中的对应板块，并参照github repo里的实现来更好的理解。

非常感谢作者百忙中回复，回复中的附件1和附件2好像没看到，对应在哪？
